### ISSUE TITLE
HSD update + database question

### ISSUE THREAD

**Issue by Omikhleia** [galadhremmin/Parf-Edhellen#31]
Greetings,

1) On `https://www.elfdict.com/about`, the following statement appears about the HSD :
> "Hiswelókë, **which haven't been updated for years**, is nonetheless still excellent, and one of the prominent sources to date on the Sindarin language."

(From a (very) quick glance at the source code, it might be in `src/resources/views/about/index.blade.php`)

Thanks for the "still excellent" wording, despite the lack of public updates until recently ;) - But regarding such updates, you may want to remove this whole statement:

The former HSD resumed and is now called "A Sindarin and Noldorin dictionary, compiled, edited and annotated by The Sindarin Dictionary Project". It's no longer referred as "Hiswelóke's", as the website was closed and its assets transferred (the articles went to Tolkiendil, the dictionary is expected to stay on JRRVF, in addition to the GitHub Page mentioned below).

Latest sources are on https://github.com/Omikhleia/sindict
A current "browsable" version is on GitHub Pages https://omikhleia.github.io/sindict/ - and (as of now) a slightly less current version is at the original address on www.jrrvf.com (for now, but it's planned to have the same version on both eventually, when some technical tasks and branch merging are completed). There is still lots do to repair that old beast and put it in a more decent state, but anyhow it no longer counts as not having been updated for years...

2) For my information, where/how can one download a copy of the Elfdict database?
I am not interested to set-up a running Parf Edhellen, but possibly just in exploring the database for the purpose of querying, analysis/comparisons and cross-checks.

Regards.

**Comment by galadhremmin** [comment]
Hi Omikhleia,

Thank you for reaching out, and *thank you* for your patience! I've been tremendously busy preparing for a move, so I have not had time to focus on what has become one of my favourite hobby projects. I'm really happy to hear that you've picked up the dictionary project once more, and I'd love to update the definitions and language accordingly. 

At the moment, I'm working to address a number of concerns raised by the owner of Eldamo. I estimate that I will be ready by the end of the week, after which I will look into addressing this request.

Regarding database access, are you primarily interested in the Hisweloke dataset, or the entire dataset? 

Thanks,
Aldaleon

**Comment by galadhremmin** [comment]
@Omikhleia 

Just following up on this thread - is the project still alive? I haven't seen an update for the last 11 months.

**Comment by Omikhleia** [comment]
Funny you ask precisely now: I am currently working on refactoring/upgrading/re-packaging the tooling used for generating the PDF version(s) of the dictionary. (This is a long standing task, and the tooling is in other repositories such as [teidict.sile](https://github.com/Omikhleia/teidict.sile) so there hasn't been anything yet "visible" on the lexicon repository itself, but I'll eventually be able to re-generated the PDFs in a hopefully nicer form or, at least, with an easier path).

As of the lexicon itself, I am not sure what updates would have been necessary in the last 11 months, after the information from the _Nature of Middle-earth_ was referenced. Unless I have missed some information published since then (which is possible, the year has been tough). (It doesn't mean that other small improvements here and there aren't still possible, but I haven't been notified of any "urgent" matter).

**Comment by galadhremmin** [comment]
Cool! I'll push refreshing the import from SINDICT up the priority stack then. Thank you! 👊🏻

**Comment by Omikhleia** [comment]
> Cool! I'll push refreshing the import from SINDICT up the priority stack then. Thank you! 

That's something **very different** from what I initially asked in this issue last year, and I am afraid it's actually not possible.

For the recap, in May 2021, I asked:
- To possibly have a now obsolete sentence that mentions Hiswelókë not being been updated for years" being fixed, to account for the update, since it's no longer true... This mere sentence is still here currently, though it would have been an easy fix by all standards...
- To inquire, about the availability of the database for cross-checks - but as I noted later, I eventually relied on other means... And anyhow the more general topic of database availability is now better addressed in #34 ...

In Oct. 2021, I also inquired regarding "what would it _mean_" the updated version taken into account (emphasis added). But I realize from #34 that the licenses are **incompatible** for this to occur, and I am **not** in a position to give any exception to it (nor did I ever said or implied such a thing, to my knowledge and according to any records I have kept). So no, I guess that's not possible (and it was likely never possible, actually...) - and I cannot endorse and even less approve any use under a license other than the current "CC-BY-NC-SA with additional limitation of scope" under which the HSD/Omikhleia material is distributed.

**Comment by galadhremmin** [comment]
I apologise for not getting to this request sooner. You didn't respond to my questions until several months later, so I assumed it wasn't an urgent request. As this is a project that I work on when I have time (usually in evenings or on weekends), the request _was_ still on my list of things to do but I didn't get to it until today. For future reference, please feel free to remind me within the task or file a pull request on your own.

> I cannot endorse and even less approve any use under a license other than the current "CC-BY-NC-SA with additional limitation of scope

If you are comfortable with my redistributing the HSD in its current form within this repository, I'd be more than glad to do so! I just meant in #34 that I didn't mention that in my ask (it was so many years ago, so I don't remember the exchange for HSD.)

**Comment by Omikhleia** [comment]
> A long time, admittedly, but I only have a few hours every other week 

Point granted, obviously...

But still....
You, according to my sindict mailing-list archives, July 20, 2011: "What is the status of this project? Has anything happened since 2008?"
And now, above: "Is the project still alive? I haven't seen an update for the last 11 months."

See how annoying it may be, when people _always_ seem to expect something from you? But darn, we are human beings. Sometimes, the extra time we'd need isn't just there for us. I don't _really_ complain that you couldn't update a _single simple_ sentence since I asked almost 1.5 year ago. I don't really care. It's too late anyway for an announcement, lol :D 

I just wrote, at the time, to some people who had used the HSD long ago... Some acknowledged the long-awaited update (or no longer awaited, heh!), and some didn't. I don't care, I've done my part in the play. But you are the one actually awakening the dragon in me with the above-quoted sentence ;-) I didn't put you under pressure, because I know the effects all too well... It took me 10 years or so to recover(*)... Still, you did put some pressure again with your "Is it still alive" question. Hey, we all do what we can, at the possible pace. No less, but no more. Sometimes, it's best to let the old dragons sleep for a while, they have other duties too ;-)

(*) Which doesn't mean nothing happened. I have other projects beside that old HSD, and [some came to fruition](https://sites.google.com/site/dragonbrumeux/publications?authuser=0).

> If you are comfortable with my redistributing the HSD

Really, you have to understand: I don't have to be comfortable with it or not. I don't have to give authorization or not for a thing or another: that would be a ill move.... The only thing I say, when asked, is "Hey folks, carefully read, there's that long license blurb in the XML and HTML (or even now PDF) files you got". It says it all, and that's _all_ I _will_ say on the matter.

**Comment by galadhremmin** [comment]
> You, according to my sindict mailing-list archives, July 20, 2011: "What is the status of this project? Has anything happened since 2008?" And now, above: "Is the project still alive? I haven't seen an update for the last 11 months."

It was certainly not my intention to "awake the dragon." I asked as you were mentioning back in the day (when we first started to engage) that you were going to make changes to the dictionary. You made it sound like it was an ongoing process. This is why I was asking, since I was coming from the direction of *"now that I'm looking at this, are there any other changes I should include?"* My disconnect is probably due to the fact that I have not engaged in the "is it dead" conversations you were referring to - I didn't know you were under such pressure by the community!

> a single simple sentence since I asked almost 1.5 year ago

Yes, I know, but if you look over the history in the last year, you'll see that I've tackled some pretty bit changes to the website. These changes were of higher priority. It might seem weird in retrospect how such a comparatively small change would take so much time, but it is "what we do with the time that is given to us" (to quote a certain sage! 😁) You might disagree with the priority, and to a certain extent, I agree that I could've done it sooner, but this has honestly been a function of my nearly mechanical obsession with prioritization due to the hectic life I've lead during the COVID19 pandemic.

I promise you that I'll update the text before the end of the week. 

> I don't have to give authorization or not for a thing or another: that would be a ill move

I get it. I really do. But you also have to understand that I have not touched the HSD import in the _last 10 years!_ It's exactly the same as it used to be! I will go ahead and make sure that there is a database dump of the derivative dataset by the end of the week.

This is a passion project for me, and I'm so grateful and impressed by the amazing work you folks have done building these dictionaries. I go back every month paying for the server capacity to keep the service running all these years, despite the ads that are a fairly recent addition. It is not my intention to seem officious and in any way disagreeable.

Thanks,
Leonard

**Comment by galadhremmin** [comment]
This issue is now resolved with 098318aa63d7912d05e621c18444307c35865eef. I've updated the description and cleared all view caches in production. You should now see _SINDICT_ as requested: https://www.elfdict.com/about.

I've also made the database available for download. I've successfully tried to restore the database using these files. Please find the files here: https://github.com/galadhremmin/Parf-Edhellen/tree/master/model

I'm now closing this issue. If you have any further questions or concerns, please feel free to reopen it.
